Osd 8474 orig
openshift/osde2e pull request #1078
Opened 2022-03-24 17:43 UTC by ritmun

2022-03-24 17:49 UTC, MrSantamaria commented
Making changes to Pr-Check:
https://github.com/openshift/release/pull/27263

2022-03-24 22:43 UTC, MrSantamaria commented
/test verify

2022-03-25 00:37 UTC, MrSantamaria commented
/test verify

2022-03-25 03:13 UTC, MrSantamaria commented
/test verify

2022-03-25 12:53 UTC, MrSantamaria commented
/test verify

2022-03-25 14:58 UTC, MrSantamaria commented
/test verify

2022-03-25 16:03 UTC, MrSantamaria commented
/test verify

2022-03-29 16:21 UTC, MrSantamaria requested changes

2022-03-29 16:27 UTC, ritmun commented on pkg/e2e/operators/cloudingress/rhapi_lb.go
> +			}, 600)
changing 10 min to 15 min

2022-03-29 16:28 UTC, ritmun commented on pkg/e2e/operators/cloudingress/rhapi_lb.go
> +			}, 600)
In my individual test it take 3-4 min max, but I changed it to 15 min, just in case.

2022-03-29 17:54 UTC, MrSantamaria commented
/test verify

2022-03-29 19:11 UTC, cblecker commented
@ritmun Would you also mind updating the PR title and body with a description of what this is doing? Thank you!

2022-03-29 19:16 UTC, MrSantamaria commented
@ritmun the timeout still seems to be the problem. Could you up this even more?

2022-03-31 15:11 UTC, ritmun commented
> @ritmun Would you also mind updating the PR title and body with a description of what this is doing? Thank you!

done

2022-03-31 22:00 UTC, MrSantamaria commented
/test verify

2022-03-31 23:27 UTC, MrSantamaria commented
@ritmun Ran it again and digging through the logs:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_osde2e/1078/pull-ci-openshift-osde2e-main-verify/1509651900734115840

SSSSSSSSSS[restful] 2022/03/31 22:18:39 log.go:30: Old LB - adae1a033fe84440585e25fec3a8f3f2 
[restful] 2022/03/31 22:18:39 log.go:30: Old LB deleted 

Then in Cloudtrail:
DeleteLoadBalancer | March 31, 2022, 16:18:39 (UTC-06:00) | sd-cicd | elasticloadbalancing.amazonaws.com | AWS::ElasticLoadBalancing::LoadBalancer | adae1a033fe84440585e25fec3a8f3f2

It seems the command to create the newLB is never launching.

2022-04-06 14:54 UTC, ritmun commented
> @ritmun Ran it again and digging through the logs: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_osde2e/1078/pull-ci-openshift-osde2e-main-verify/1509651900734115840
> 
> SSSSSSSSSS[restful] 2022/03/31 22:18:39 log.go:30: Old LB - adae1a033fe84440585e25fec3a8f3f2 [restful] 2022/03/31 22:18:39 log.go:30: Old LB deleted
> 
> Then in Cloudtrail: DeleteLoadBalancer | March 31, 2022, 16:18:39 (UTC-06:00) | sd-cicd | elasticloadbalancing.amazonaws.com | AWS::ElasticLoadBalancing::LoadBalancer | adae1a033fe84440585e25fec3a8f3f2
> 
> It seems the command to create the newLB is never launching.

Looks like the service deletion never finishes. Maybe that service is in use. Are we sure no other tests are running in parallel on this cluster at the same time? I'll add some logs to debug.

2022-04-06 23:29 UTC, ritmun commented
> > @ritmun Ran it again and digging through the logs: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_osde2e/1078/pull-ci-openshift-osde2e-main-verify/1509651900734115840
> > SSSSSSSSSS[restful] 2022/03/31 22:18:39 log.go:30: Old LB - adae1a033fe84440585e25fec3a8f3f2 [restful] 2022/03/31 22:18:39 log.go:30: Old LB deleted
> > Then in Cloudtrail: DeleteLoadBalancer | March 31, 2022, 16:18:39 (UTC-06:00) | sd-cicd | elasticloadbalancing.amazonaws.com | AWS::ElasticLoadBalancing::LoadBalancer | adae1a033fe84440585e25fec3a8f3f2
> > It seems the command to create the newLB is never launching.
> 
> Looks like the service deletion never finishes. Maybe that service is in use. Are we sure no other tests are running in parallel on this cluster at the same time? I'll add some logs to debug.

@MrSantamaria  Also, the LB deleted in AWS is from another test. Our LB should be adae1a033fe84440585e25fec3a8f3f2 which isn't being deleted. I've added more logs in the output.

2022-04-06 23:34 UTC, ritmun commented
@MrSantamaria  does the SA have required permission to delete this ELB? Just want to rule that out.

2022-04-07 01:05 UTC, ritmun commented
Ok, I dug a bit into this. None of the aws client requests are going through. Something with the credential change is affecting this. Could you (@MrSantamaria ) look at the recent changes to creds and check if rhapi_lb.go test is affected by it?  I'm also  going to do the same.

2022-04-07 16:31 UTC, MrSantamaria commented
/test verify

2022-04-07 20:18 UTC, MrSantamaria commented
/test verify

2022-04-12 03:05 UTC, MrSantamaria commented
Adding James as a reviewer as well since I'm looking to meet with him on this issue. 
From what I can tell we are currently running into an AWS account mismatch. The AWS Prod account I'm passing doesn't seem to be the correct account for the OSDe2e Prod jobs. 

The code is working as intended but we are sending the wrong account a request to delete the vpc.

2022-04-12 20:33 UTC, ritmun reviewed
(comment submitted while trying to close the outdated "change requested" items showing on PR. )

2022-04-12 20:37 UTC, ritmun commented
@MrSantamaria just wanted to leave a reminder - if any more changes are needed to fix this PR, if possible, please branch off of this branch (`osd-8474-orig`) and PR back into it. It will be much quicker than fixing them on `main` branch and then pulling them into this branch.  I'll keep this branch up to date with `main`.

2022-04-12 21:53 UTC, MrSantamaria commented
I've met with @jharrington22 on the AWS account issue we are seeing in the pr-check. 
I created this PR-Check cluster manually so it sits in a Red Hat Managed account but I will recreate it to use SD-CICD's CCS account. 

For AWS to test this fully there are three scenarios:
Manual Install(That's how I setup the pr-check cluster)
CloudCredentialOperator
CloudIngressOperator in the namespace
https://github.com/openshift/cloud-ingress-operator/blob/master/pkg/cloudclient/aws/aws.go#L110-L128

CCS Install -> This is the current logic and it will work once I make the above change. 

STS tokens -> This one might be tricky to get done.

2022-04-12 23:34 UTC, MrSantamaria commented
/test verify

2022-04-13 02:10 UTC, ritmun commented
I've made a squashed PR https://github.com/openshift/osde2e/pull/1098

2022-04-13 02:23 UTC, ritmun commented
/hold

2022-04-18 16:37 UTC, closed without merging