SDCICD-856 generic test harness runner, suite and template
openshift/osde2e pull request #1449
Opened 2022-12-07 22:20 UTC by ritmun

jira: [SDCICD-856 ](https://issues.redhat.com/browse/SDCICD-856)

Generic  test harness  to run given test harness image

To test locally, build the binary, then:
```
HARNESS_IMAGES=quay.io/rmundhe_oc/avo-test-harness  HARNESS_POLLING_TIMEOUT=200 ./out/osde2e -- test --configs rosa,stage,harness-suite l --must-gather false --destroy-cluster false --skip-health-check true
```

`osde2e` accepts "HARNESS_IMAGES" env var and utilizes a template which spins up a job in an osde2e namespace. This namespace should contain a job runner pod and a test pod. Test pod contains test-harness and push-result containers.

The mechanism of running the test image is similar to addons, but this change does not alter or utilize any existing addon harness code. 
Config(Harness struct),env var (HARNESS_IMAGES etc) are new. 
Test runner and template are almost replicas of addon runner and template.

(Passthrough keys are allowed, but not tested in this change. )

Result: Output files should be dumped in your local test-output directory.  Currently there's a single assertion within the test image, which should fail as it checks for a non-existent CRD. 
The image is currently in my dev repo, and there's a separate jira to fix the assertion and move it to app-sre quay

2022-12-07 22:49 UTC, MrSantamaria commented
Why do we want to copy/paste the addon flow into this logic? 
It would be better to turn the addon harness into a test harness logic that can be used by operator test and addons instead

2022-12-07 23:21 UTC, jbpratt requested changes
I'm very interested in us having some conversations to better understand what osde2e as a test runner/harness looks like internally. The use of gomega throws me off, a lot of functionality within osde2e is written using gomega like it is a test, not handling the error but just assert/failing on the spot. (cc @MrSantamaria )

Left a few comments! Thanks :cat:

2022-12-08 19:59 UTC, closed without merging

2022-12-08 20:01 UTC, ritmun commented
@jbpratt thanks for your comments, I can possibly incorporate some of the changes in addon flow when I make the new PR.

2022-12-08 20:02 UTC, ritmun commented on pkg/common/helper/harnesses.go
> +// GEneralizd harness runner: Essentially replicates addon harness runner, with generalized harness template
It can be, but I didn't want to affect existing addon flow. I can probably achieve this in my next PR which uses addon flow in a generic way.