Upload results to s3 bucket if LOG_BUCKET is set
openshift/osde2e pull request #2244
Opened 2023-11-21 20:51 UTC by ritmun

Why?:

- E2e harness jobs running on tekton do not provide any useful logs nor junit result files. Result files are immediately destroyed after job runs, pod logs are destroyed on hive on next run. 
- This s3 PR is a viable option to persist pod logs from tekton jobs at this point.

What?:

- IF “LOG_BUCKET” is provided, result files will get uploaded under job folder in s3
- Files will be deleted after one month, this is set by a Lifecycle Rule on the bucket.
- Reuses existing code to upload things to s3 

Alternative solution to blocking card https://issues.redhat.com/browse/APPSRE-8362

2023-11-27 12:06 UTC, jbpratt requested changes

2023-11-27 12:06 UTC, jbpratt commented on pkg/e2e/harness_runner/harness_runner.go
> +				err = h.UploadResultsToS3(results, harnessImage+time.DateTime)
`time.DateTime` is a constant, I don't think that is what you are wanting to use https://pkg.go.dev/time#pkg-constants

(note the name of your S3 buckets, the date is 2006)

2023-11-28 12:05 UTC, jbpratt commented
/label tide/merge-method-squash

2023-11-29 21:02 UTC, MrSantamaria commented on pkg/common/helper/runner.go
> +		if err != nil {
Spoke about this on [slack](https://redhat-internal.slack.com/archives/CMK13BP4J/p1701291454368849?thread_ts=1701290461.809129&cid=CMK13BP4J)

2023-11-29 21:23 UTC, MrSantamaria commented on pkg/common/helper/runner.go
> +		session, err := aws.CcsAwsSession.GetSession()
To follow up as tech debt to add s3_session as part of the session.go

2023-11-29 21:26 UTC, MrSantamaria commented on pkg/common/aws/s3.go
> +func WriteToS3Session(session *session.Session, outputKey string, data []byte) error {
We spoke about this in a huddle. We are leaving it as a feature which will use 1 aws account in the future.

2023-11-29 21:26 UTC, MrSantamaria commented
/lgtm

2023-11-29 21:31 UTC, merged