sdcicd-1201 Create blocking cluster healthcheck test spec
openshift/osde2e pull request #2298
Opened 2024-01-17 23:26 UTC by ritmun

What?:
Created test suite for blocking osd-cluster-ready check

Why:
To enable running osd-cluster-ready as a ginkgo test spec instead of set-up  

Jira:
[sdcicd-1201](https://issues.redhat.com//browse/sdcicd-1201)

[x] tested locally on a stage cluster

2024-01-18 08:11 UTC, jbpratt requested changes
I think simply checking the job like this should work for now. The mcscupgrade suite kicks the job to watch it succeed again, after the case of an upgrade which we don't need to worry about for now. 

https://github.com/openshift/osde2e/blob/2378d6040935ed86ba15bed2a498b1742064c9a2/test/mcscupgrade/mcscupgrade_test.go#L365

2024-01-18 08:12 UTC, jbpratt commented on pkg/e2e/openshift/osdclusterready.go
> +		defer cancel()
You can also use ginkgo timeout instead of setting up a new context to timeout

2024-01-19 11:12 UTC, jbpratt commented on pkg/e2e/openshift/osdclusterready.go
While I understand it wasn't mention, this has been something we have been pushing for a few months (hence the directory existing to begin with). The direction we want to move is to be able to execute things with ginkgo directly. Adding this to e2e means we can't do that. The test runner is ginkgo IMO, we are orchestrating everything else in prow.

2024-01-19 11:13 UTC, jbpratt commented on pkg/common/cluster/healthchecks/healthcheckjob.go
> +						data, err := k8sClient.CoreV1().Pods(namespace).GetLogs(pod.Name, &v1.PodLogOptions{}).DoRaw(context.TODO())
```suggestion
						data, err := k8sClient.CoreV1().Pods(namespace).GetLogs(pod.Name, &v1.PodLogOptions{}).DoRaw(ctx)
```

2024-01-19 16:13 UTC, mmazur commented on pkg/e2e/openshift/osdclusterready.go
If the code scaffolding doesn't already exist to easily do it in the new way, please do it in the current way. The point of the epic was to do it with minimal code changes and we're sticking to that.

If I understand this discussion correctly, I'm fairly certain we'll want to do the changes Brady mentions as part of the followup epics, but I'll  want us to have a longer architectural discussion before that happens.

2024-01-22 09:09 UTC, jbpratt commented on pkg/e2e/openshift/osdclusterready.go
> +		defer cancel()
Unresolving this, no changes have been made

2024-01-22 09:09 UTC, jbpratt commented on pkg/e2e/openshift/osdclusterready.go
> +		joberr := WatchJob(k8s, ctx, *job)
this can be simplified with https://github.com/openshift/osde2e-common/pull/61

2024-01-22 09:09 UTC, jbpratt commented on pkg/e2e/openshift/osdclusterready.go
> +			logs, err = k8s.GetJobLogs(ctx, jobname, namespace)
need to check err

2024-01-22 09:10 UTC, jbpratt commented on pkg/e2e/openshift/osdclusterready.go
> +var jobname = "osd-cluster-ready"
please make these constants and I feel like it should be formatted differently via gofmt

2024-01-22 09:11 UTC, jbpratt commented on pkg/e2e/openshift/osdclusterready.go
> +		Expect(err).ShouldNot(HaveOccurred(), "failed to parse duration")
Is there a reason we don't just make a `var timeout = 30 * time.Minute` object? It is already a constant at the top of the file

2024-01-22 21:22 UTC, closed without merging