Test to verify dedicated admin can not create subjectpermissions CR
openshift/osde2e pull request #612
Opened 2020-10-28 18:58 UTC by aliceh

This commit adds tests to verify that dedicated-admins are not allowed to create subjectpermissions CRs and cluster admins are.

2020-10-28 19:51 UTC, jeefy requested changes
Couple questions/changes, overall looks good!

2020-10-28 19:51 UTC, jeefy commented on pkg/e2e/operators/rbac.go
> +	checkSubjectPermissions(h, "sre-admins")
Are `checkSubjectpernission` and `daCreateSubjectpernission` Spelling errors? I see that it's a separately-defined function, but it's so similarly named that I did a double-take. Could this be made clearer?

2020-10-28 19:51 UTC, jeefy commented on pkg/e2e/operators/rbac.go
> +func makeSubjectpermission(name string) api.SubjectPermission {
This should probably be `makeSubjectPermission`

2020-10-28 19:51 UTC, jeefy commented on pkg/e2e/operators/rbac.go
> +	daCreateSubjectpernission(h)
`daCreateSubjectpernission` and `checkSubjectpernission` aren't reused. I would put their ginkgo Context blocks back under the Describe block, there's no benefit to breaking these out into separate functions.

2020-10-30 20:56 UTC, aliceh commented
@jeefy, thanks for reviewing! I updated the code accordingly.

2020-11-02 13:20 UTC, jeefy commented
/approve

2020-11-10 22:41 UTC, clcollins approved these changes
/lgtm

2020-11-11 01:56 UTC, merged