Scc test to verify new Scc does not break pods
openshift/osde2e pull request #687
Opened 2021-02-04 03:04 UTC by aliceh

In this commit, I added a test that creates a new permissive Scc and then restarts the prometheus and ssh pods. Nest, the test verifies that the new pods came up as expected. This test was created to verify the fix for Bug 1868976 https://bugzilla.redhat.com/show_bug.cgi?id=1868976

2021-02-04 19:12 UTC, whereswaldon requested changes
I have a few questions about the implementation, but it looks good at a high level. Nice work! What a gnarly bug.

2021-02-04 19:12 UTC, whereswaldon commented on pkg/e2e/verify/sccs.go
> +	podNames = nil
```suggestion
```
The zero value for a slice is already nil, so this is a no-op.

2021-02-04 19:12 UTC, whereswaldon commented on pkg/e2e/verify/sccs.go
> +	}
```suggestion
	}
	total = len(list.Items)
	numReady = (total - len(notReady))
```

I can't see any reason to recompute these values each loop iteration. Am I missing something?

2021-02-04 19:12 UTC, whereswaldon commented on pkg/e2e/verify/sccs.go
> +		sc = *s
```suggestion
```
I have the sense that I'm probably just missing some k8s context here, but why do we need to fetch the scale again? We already have the version of it with zero replicas in the local variable `sc`. Can't we just update that one and apply it again?

2021-02-05 18:32 UTC, aliceh commented
Thanks for the useful suggestions, @whereswaldon !

2021-02-05 20:10 UTC, whereswaldon approved these changes

2021-02-05 20:10 UTC, whereswaldon commented
/approve

You're welcome! Looks good.

2021-02-05 20:50 UTC, jeefy commented
/lgtm

2021-02-05 21:03 UTC, merged