OAuth token timeout tests
openshift/osde2e pull request #756
Opened 2021-03-23 08:08 UTC by gsleeman

Tests for the presence of timeout values in the global oauth token config, and tests whether inactivity timeouts are working for oauthaccesstokens

Some of these tests are expected to fail until https://github.com/openshift/managed-cluster-config/pull/766 is in prod

2021-04-30 20:10 UTC, whereswaldon requested changes
This looks reasonable to me, though we do need to switch to a thread-safe viper.

Have you tested this locally?

2021-05-03 10:36 UTC, gsleeman commented on pkg/e2e/verify/oauth_tokens.go
> +	"github.com/spf13/viper"
Thanks for that.

I've tested locally with a kubeconfig and focus test. Do I need to do a full test run as well?

2021-05-03 13:44 UTC, whereswaldon commented on pkg/e2e/verify/oauth_tokens.go
> +	"github.com/spf13/viper"
No, the focus test is sufficient.

2021-05-03 13:45 UTC, whereswaldon approved these changes

2021-05-03 13:45 UTC, whereswaldon commented
/approve

2021-05-03 13:45 UTC, whereswaldon commented
/assign @jeefy

2021-05-03 13:59 UTC, jeefy commented
/lgtm

2021-05-03 14:05 UTC, merged