SDCICD-581 / 647: Surface exit codes from RunTests, exit(130) if an issue with version selection
openshift/osde2e pull request #824
Opened 2021-05-12 17:23 UTC by jeefy

This PR allows us to provide an exit code we want `osde2e test` to use during `RunTests` / `runGinkgoTests`. 

In addition, it updates version selection/errors to exit(130) when an issue arrises during version selection.

2021-05-12 20:01 UTC, whereswaldon requested changes
Lookin' good! Two things: a behavior change question in the code, and a higher-level request:

Can we define
```
const Success = 0
const Failure = 1
const Aborted = 130
```
and then just return these constants?

2021-05-13 23:19 UTC, jeefy commented on cmd/osde2e/test/cmd.go
> +		log.Printf("error loading initial state: %v", err)
We should, good point.

2021-05-14 16:33 UTC, whereswaldon approved these changes
/lgtm

2021-05-17 16:30 UTC, whereswaldon approved these changes
/lgtm

2021-05-17 16:46 UTC, merged