[OSD-7306] Adding a secondary router test for cloud ingress operator
openshift/osde2e pull request #853
Opened 2021-06-10 07:07 UTC by bng0y

2021-06-10 15:27 UTC, jeefy commented
/approve

2021-06-10 16:36 UTC, whereswaldon requested changes
A single typo in the test name, but that's all. Looking good!

2021-06-10 16:36 UTC, whereswaldon commented on pkg/e2e/operators/cloudingress/secondary_router.go
> +		ginkgo.It("should be deleted when removed to publishingstrategy", func() {
```suggestion
		ginkgo.It("should be deleted when removed from publishingstrategy", func() {
```

2021-06-11 11:06 UTC, bng0y commented on pkg/e2e/operators/cloudingress/secondary_router.go
> +		ginkgo.It("should be deleted when removed to publishingstrategy", func() {
Thanks. I will change that

2021-06-21 06:28 UTC, bng0y commented on pkg/e2e/operators/cloudingress/secondary_router.go
> +		ginkgo.It("should be deleted when removed to publishingstrategy", func() {
solved

2021-06-21 14:15 UTC, whereswaldon approved these changes
/lgtm

2021-06-21 14:16 UTC, merged