Passing ocm-token from osde2e secrets for addons to use
openshift/osde2e pull request #997
Opened 2022-01-19 22:48 UTC by MrSantamaria

2022-01-20 17:34 UTC, jeefy requested changes
Logic looks good, just need to clean up the code a bit :)

2022-01-20 17:34 UTC, jeefy commented on pkg/common/load/load.go
> +					passthruSecrets["ocm-token-refresh"] = viper.Get("ocm.token").(string)
You should be do `viper.GetString("ocm.token")` rather than casting `Get`'s output to a string.

2022-01-20 17:34 UTC, jeefy commented on pkg/common/load/load.go
> +				fmt.Printf(path)
Probably an artifact from debugging, remove

2022-01-20 17:34 UTC, jeefy commented on pkg/common/load/load.go
> +				fmt.Printf(info.Name())
Probably an artifact from debugging, remove

2022-01-20 22:03 UTC, MrSantamaria commented
Made review changes

2022-01-21 19:18 UTC, jeefy commented
/approve
/lgtm

2022-01-21 19:21 UTC, merged